[profile.default]
status-level = "skip"
success-output = "immediate"

[profile.quiet]
success-output = "never"

[profile.ci]
success-output = "never"
failure-output = "final"
fail-fast = false
junit = { path = "cargo-tests.xml" }
